version: '3.9'

services:
  mariadb: 
    image: mariadb:10.10.2
    restart: always
    container_name: ${DB_HOST}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 13306:3306
    networks:
      - pashminanepal
    volumes:
      - pashminaDbData:/var/lib/mysql

  pashmina-nepal:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pashminanepal_api
    restart: always
    command: yarn start:dev
    env_file:
      - .env
    environment:
      - PORT=${PORT}
    ports:
      - 3001:3000
    networks:
      - pashminanepal
    depends_on:
      - mariadb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
networks:
  pashminanepal:
volumes:
  pashminaDbData:
